# -*- coding: utf-8 -*-
"""Decision Tree Cassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HyhD2y9nhouzCJjs4lr2iQOwzxIaCW5w

# PROGRAM STATEMENT

Write a program to implement Decision Tree Classification on given data set to design
a model that can predict whether the player will play on a given day on the basis of the
provided features.

# CODE
"""

# The dataset in the form of lists
# weather, outlook, humidity, wind are features
# play is the target
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast',
         'Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
outlook=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild',
         'Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes',
      'Yes','Yes','Yes','No']
humidity=['High', 'High','High','High','Normal','Normal','Normal',
          'High','Normal','Normal','Normal','High','Normal','High' ]
wind=['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak',
      'Weak','Weak','Strong','Strong','Weak','Strong']

# Now we have to convert this lists into numpy arrays
# So we need Label Encoding
# Import LabelEncoder
from sklearn import preprocessing
# creating LabelEncoder
le = preprocessing.LabelEncoder()

# Label Encoding for the feature Weather
wthr_encoded = le.fit_transform(weather)
print("The classes are: ", le.classes_)
print("The encoded array is: ", wthr_encoded)

# Label Encoding for the feature Outlook
otlk_encoded = le.fit_transform(outlook)
print("The classes are: ", le.classes_)
print("The encoded array is: ", otlk_encoded)

# Label Encoding for the feature Humidity
hdty_encoded = le.fit_transform(humidity)
print("The classes are: ", le.classes_)
print("The encoded array is: ", hdty_encoded)

# Label Encoding for the feature Wind
wind_encoded = le.fit_transform(wind)
print("The classes are: ", le.classes_)
print("The encoded array is: ", wind_encoded)

# Label Encoding for the target
y = le.fit_transform(play)
print("The classes are: ", le.classes_)
print("The encoded array is: ", y)

# Now we have to merge the four features into one array
zipped = zip(wthr_encoded, otlk_encoded, hdty_encoded, wind_encoded)

# zipped is an object we have to convert it to list
import numpy as np
X = np.array(list(zipped)).tolist()

print("The features set: ")
X

# Importing the Decision Tree Classifier
from sklearn import tree
# Instantiating the classifier
model = tree.DecisionTreeClassifier(criterion = 'entropy')
# Train the model using the whole set
model.fit(X, y)

# Plotting the Decision Tree
from matplotlib import pyplot as plt
fig, ax = plt.subplots(figsize=(10, 10))
tree.plot_tree(model,ax=ax,feature_names=['weather','outlook','humidity','wind'])
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !wget -nc https://raw.githubusercontent.com/brpy/colab-pdf/master/colab_pdf.py
# from colab_pdf import colab_pdf
# colab_pdf('Decision Tree Cassifier.ipynb')